name: Add issue to project

on:
  issues:
    types:
      - opened

jobs:
  add-issue-to-project:
    uses: AutomatikVFX/.github/.github/workflows/add-issue-to-project.yml@main
    secrets:
      github-token: ${{ secrets.ADD_ISSUE_TO_PROJECT_PAT }}
