name: Add pr to project

on:
  pull_request:
    types: 
      - opened

jobs:
  add-pr-to-project:
    uses: AutomatikVFX/.github/.github/workflows/add-pr-to-project.yml@main
    secrets:
      github-token: ${{ secrets.ADD_PR_TO_PROJECT_PAT }}